### ISSUE TITLE
:fire: fish-25/docs 파일 명 일관성 있게 수정

### ISSUE THREAD

**Issue by shirohoo** [telos-projects/fish-25#14]
![image](https://user-images.githubusercontent.com/71188307/163507615-e791c34f-4923-4167-a344-7c0c1065773f.png)

수정 후 예시

- CODE_OF_CONDUCT.adoc
- FISH_25.png
- KOTLIN_CODE_STYLE.xml

<br />

**Comment by Junnyjun** [comment]
수고하셨습니다
